config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'music', to: 'pages#music'
  resources :games, only: :index
  resources :movies, only: :index
  resources :messages, only: :create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :photo
end

app/models/message.rb
class Message < ApplicationRecord
  validates :email, :subject, :content, presence: true
  after_create :send_email

  private

  def send_email
    MessageMailer.with(message: self).new.deliver_now
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  scope :published, -> { where(published: true) }
  PRIORITY = %w[hight medium low]
  enum priority: PRIORITY
  has_one_attached :photo
  paginates_per 10
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/reward.rb
class Reward < ApplicationRecord
  default_scope { order(year: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.order(year: :desc, title: :asc).page(params[:page])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  invisible_captcha only: :create

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "Message successfully sent. Thanks!"
      redirect_to contact_path
    else
      render 'pages/contact'
    end
  end

  private

  def message_params
    params.require(:message).permit(:email, :subject, :content)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.published.order(as_assistant: :asc, year: :desc, priority: :asc, title: :asc).page(params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @rewards = Reward.all
    @page = Page.find_by(slug: 'informations')
  end

  def contact
    @message = Message.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate(string, max_length)
    str = string.to_s
    if str.length > max_length
      str[0...max_length] + "..."
    else
      str
    end
  end

  def instance_image_tag(photo, options = {})
    if photo.attached?
      cl_image_tag photo.key, options
    else
      image_tag "no-picture.png", options
    end
  end

  def emoji(content)
    Twemoji.parse(content, img_attrs: {style: "height: 1em; margin: 0px;"}).html_safe
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/games/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <% @games.each do |game| %>
        <div class="project-card">
          <div class="picture">
            <% if game.link? %>
              <%= link_to game.link, target: "_blank" do %>
                <%= instance_image_tag game.photo, height: 300, width: 220, crop: :fill %>
              <% end %>
            <% else %>
              <%= instance_image_tag game.photo, height: 300, width: 220, crop: :fill %>
            <% end %>
          </div>
          <div class="content">
            <% if game.link? %>
              <h2><%= link_to game.title, game.link, target: "_blank" %></h2>
            <% else %>
              <h2><%= game.title %></h2>
            <% end %>
            <% if game.genre? %>
              <p class="type"><%= game.genre %></p>
            <% end %>
            <% if game.year? %>
              <p class="details"><span><%= game.year %></span></p>
            <% end %>
            <% if game.developer? %>
              <p class="details">Developed by <span><%= game.developer %></span></p>
            <% end %>
            <% if game.editor? %>
              <p class="details">Edited by <span><%= game.editor %></span></p>
            <% end %>
            <% if game.role? %>
              <br>
              <p class="details">Role <span><%= game.role %></span></p>
              <% if game.composer? %>
                <p class="details">Composer <span><%= game.composer %></span></p>
              <% end %>
            <% end %>
            <% if game.informations? %>
              <div class="rewards"><%= simple_format game.informations %></div>
            <% end %>
          </div>
        </div>
        <div class="project-card-mobile">
          <div class="project-data">
            <div class="picture">
              <% if game.link? %>
                <%= link_to game.link, target: "_blank" do %>
                  <%= instance_image_tag game.photo, height: 150, width: 110, crop: :fill %>
                <% end %>
              <% else %>
                <%= instance_image_tag game.photo, height: 150, width: 110, crop: :fill %>
              <% end %>
            </div>
            <div class="title">
              <% if game.link? %>
                <h2><%= link_to game.title, game.link, target: "_blank" %></h2>
              <% else %>
                <h2><%= game.title %></h2>
              <% end %>
              <% if game.genre? %>
                <p class="type"><%= game.genre %></p>
              <% end %>
            </div>
          </div>
          <div class="content">
            <% if game.year? %>
              <p class="details"><span><%= game.year %></span></p>
            <% end %>
            <% if game.developer? %>
              <p class="details">Developed by <span><%= game.developer %></span></p>
            <% end %>
            <% if game.editor? %>
              <p class="details">Edited by <span><%= game.editor %></span></p>
            <% end %>
            <% if game.role? %>
              <br>
              <p class="details">Role <span><%= game.role %></span></p>
              <% if game.composer? %>
                <p class="details">Composer <span><%= game.composer %></span></p>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="pagination">
        <%= link_to_prev_page @games, 'Previous' %>
        <%= link_to_next_page @games, 'Next' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'logo_max-herve.png' %>
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <% @movies.each do |movie| %>
        <div class="project-card">
          <div class="picture">
            <% if movie.link? %>
              <%= link_to movie.link, target: "_blank" do %>
                <%= instance_image_tag movie.photo, height: 300, width: 220, crop: :fill %>
              <% end %>
            <% else %>
              <%= instance_image_tag movie.photo, height: 300, width: 220, crop: :fill %>
            <% end %>
          </div>
          <div class="content">
            <% if movie.link? %>
              <h2><%= link_to movie.title, movie.link, target: "_blank" %></h2>
            <% else %>
              <h2><%= movie.title %></h2>
            <% end %>
            <div class="d-flex">
              <% if movie.movie_type? || movie.genre? %>
                <p class="type"><%= movie.genre %><%= ' / ' if movie.genre? %><%= movie.movie_type %></p>
              <% end %>
            </div>
            <% if movie.year? %>
              <p class="details"><span><%= movie.year %></span></p>
            <% end %>
            <% if movie.director? %>
              <p class="details">Directed by <span><%= movie.director %></span></p>
            <% end %>
            <% if movie.casting? %>
              <p class="details">Casting <span><%= movie.casting %></span></p>
            <% end %>
            <% if movie.production? %>
              <p class="details">Produced by <span><%= movie.production %></span></p>
            <% end %>
            <% if movie.as_assistant? %>
              <br>
              <p class="details">Role <span>Assistant</span></p>
              <p class="details">Composer <span><%= movie.composer %></span></p>
            <% end %>
            <% if movie.informations? %>
              <div class="rewards"><%= simple_format movie.informations %></div>
            <% end %>
          </div>
        </div>
        <div class="project-card-mobile">
          <div class="project-data">
            <div class="picture">
              <% if movie.link? %>
                <%= link_to movie.link, target: "_blank" do %>
                  <%= instance_image_tag movie.photo, height: 150, width: 110, crop: :fill %>
                <% end %>
              <% else %>
                <%= instance_image_tag movie.photo, height: 150, width: 110, crop: :fill %>
              <% end %>
            </div>
            <div class="title">
              <% if movie.link? %>
                <h2><%= link_to movie.title, movie.link, target: "_blank" %></h2>
              <% else %>
                <h2><%= movie.title %></h2>
              <% end %>
              <div class="d-flex">
                <% if movie.movie_type? || movie.genre? %>
                  <p class="type"><%= movie.genre %><%= ' / ' if movie.genre? %><%= movie.movie_type %></p>
                <% end %>
              </div>
            </div>
          </div>
          <div class="content">
            <% if movie.year? %>
              <p class="details"><span><%= movie.year %></span></p>
            <% end %>
            <% if movie.director? %>
              <p class="details">Directed by <span><%= movie.director %></span></p>
            <% end %>
            <% if movie.casting? %>
              <p class="details">Casting <span><%= movie.casting %></span></p>
            <% end %>
            <% if movie.production? %>
              <p class="details">Produced by <span><%= movie.production %></span></p>
            <% end %>
            <% if movie.as_assistant? %>
              <p class="details">Role <span>Assistant</span></p>
              <p class="details">Composer <span><%= movie.composer %></span></p>
            <% end %>
            <% if movie.informations? %>
              <div class="rewards"><%= simple_format movie.informations %></div>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="pagination">
        <%= link_to_prev_page @movies, 'Previous' %>
        <%= link_to_next_page @movies, 'Next' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="wrapper-800">
    <div class="row">
      <div class="col">
        <h1 class="h5 mb-4">Contact</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-12 col-md-4">
        <%= image_tag "MAXIMEHERVE_PORTRAIT.jpg", alt: "Maxime Hervé - French music composer based in Paris", class: "w-100" %>
        <p class="text-muted text-end fw-lighter small mb-4">photo credit: Alex Legallet</p>
      </div>
      <div class="col-12 col-md-8">
        <%= simple_form_for @message, html: { class: "contact-form mb-5" } do |f| %>
          <%= invisible_captcha %>
          <%= f.input :email, label: false, placeholder: "your@email.com", wrapper_html: {class: "mb-2"} %>
          <%= f.input :subject, label: false, placeholder: "Type the object of your message here", wrapper_html: {class: "mb-2"} %>
          <%= f.input :content, label: false, placeholder: "Type your message here", input_html: { rows: 8 }, wrapper_html: {class: "mb-2"} %>
          <div class="d-flex justify-content-end">
            <%= f.submit "Send message", class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <hr>
        <p>For <strong>video games</strong> purpose: <a href = "mailto: contact@g4f.fr">contact@g4f.fr</a></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="wrapper-800">
        <%= image_tag "MAXIMEHERVE_TMAX400.jpg", alt: "Maxime Hervé - Music composer in Paris", class: "w-100" %>
        <p class="text-muted text-end fw-lighter small">photo credit: Alex Legallet</p>
        <div class="mt-4 mb-5">
          <ul class="nav nav-tabs justify-content-end mb-3" id="bio" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="en-tab" data-bs-toggle="tab" data-bs-target="#en" type="button" role="tab" aria-controls="en" aria-selected="true"><%= emoji(":flag-gb:") %></button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="fr-tab" data-bs-toggle="tab" data-bs-target="#fr" type="button" role="tab" aria-controls="fr" aria-selected="false"><%= emoji(":flag-fr:") %></button>
            </li>
          </ul>
          <div class="tab-content" id="bioContent">
            <div class="tab-pane fade show active" id="en" role="tabpanel" aria-labelledby="en-tab">
              <%= @page.content_en.html_safe %>
            </div>
            <div class="tab-pane fade" id="fr" role="tabpanel" aria-labelledby="fr-tab">
              <%= @page.content_fr.html_safe %>
            </div>
          </div>
        </div>
        <div class="infos-rewards mt-3">
          <h1 class="h4">REWARDS</h1>
          <% @rewards.each do |reward| %>
            <div class="award d-flex">
              <p>
                <span><%= reward.year %></span>
              </p>
              <p><%= reward.description %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/music.html.erb
<div class="container">
  <div class="wrapper-800">
    <div class="row">
      <div class="col">
        <h1 class="h5 mb-4">Music playlist</h1>

        <iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1154599165&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
        <!-- <iframe width="100%" height="300" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1154599165&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe> -->

        <h2 class="h6 mt-3">Also on</h2>
        <ul class="list-unstyled">
          <li class="ms-2 mb-2">
            <%= link_to "https://open.spotify.com/artist/2LCWayrRO11GMlRVqnmHpK", class: "link-dark", target: "_blank" do %>
              <i class="fa-brands fa-spotify me-1"></i> Spotify
            <% end %>
          </li>
          <li class="ms-2 mb-2">
            <%= link_to "https://itunes.apple.com/ca/artist/maxime-herv%C3%A9/id1444851749", class: "link-dark", target: "_blank" do %>
              <i class="fa-brands fa-apple me-1"></i> Apple Music
            <% end %>
          </li>
          <li class="ms-2 mb-2">
            <%= link_to "https://www.deezer.com/fr/artist/57169412", class: "link-dark", target: "_blank" do %>
              <i class="fa-brands fa-deezer me-1"></i> Deezer
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<ul class="navbar-mh">
  <li>
    <%= link_to "Home", root_path, class: "#{'active' if params[:action].include?('home')}" %>
  </li>
  <li>
    <%= link_to "Films", movies_path, class: "#{'active' if params[:controller].include?('movie')}" %>
  </li>
  <li>
    <%= link_to "Games", games_path, class: "#{'active' if params[:controller].include?('game')}" %>
  </li>
  <li>
    <%= link_to "IMDB", "https://www.imdb.com/name/nm7161845/", target: "_blank" %>
  </li>
  <li>
    <%= link_to "Music", music_path, class: "#{'active' if params[:action].include?('music')}" %>
  </li>
  <li>
    <%= link_to "Contact", contact_path, class: "#{'active' if params[:action].include?('contact')}" %>
  </li>
</ul>
<div class="mobile-menu-mh" data-controller="css" data-css-class="show">
  <div class="burger" data-action="click->css#toggleClass">
    <div></div>
    <div></div>
    <div></div>
  </div>
  <div class="mask"></div>
  <ul>
    <li>
      <%= link_to "Home", root_path, class: "#{'active' if params[:action].include?('home')}" %>
    </li>
    <li>
      <%= link_to "Films", movies_path, class: "#{'active' if params[:controller].include?('movie')}" %>
    </li>
    <li>
      <%= link_to "Games", games_path, class: "#{'active' if params[:controller].include?('game')}" %>
    </li>
    <li>
      <%= link_to "IMDB", "https://www.imdb.com/name/nm7161845/", target: "_blank" %>
    </li>
    <li>
      <%= link_to "Music", music_path, class: "#{'active' if params[:action].include?('music')}" %>
    </li>
    <li class="mb-5">
      <%= link_to "Contact", contact_path, class: "#{'active' if params[:action].include?('contact')}" %>
    </li>
    <li class="music">
      <%= link_to "Spotify", "https://open.spotify.com/artist/2LCWayrRO11GMlRVqnmHpK", target: "_blank" %>
    </li>
    <li class="music">
      <%= link_to "Apple Music", "https://itunes.apple.com/ca/artist/maxime-herv%C3%A9/id1444851749", target: "_blank" %>
    </li>
    <li class="music">
      <%= link_to "Deezer", "https://www.deezer.com/fr/artist/57169412", target: "_blank" %>
    </li>
  </ul>
</div>